//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alphabetical_list_of_products
    {
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string QuantityPerUnit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<long> UnitsInStock { get; set; }
        public Nullable<long> UnitsOnOrder { get; set; }
        public Nullable<long> ReorderLevel { get; set; }
        public string Discontinued { get; set; }
        public string CategoryName { get; set; }
    }
}
